[supervisord]
nodaemon=true
user=root

[program:rsyslog]
command=rsyslogd -n -x
priority=80

[program:cyrusimap]
command=/usr/sbin/cyrmaster -M /etc/cyrus-conf/cyrus.conf -C /etc/cyrus-conf/imapd.conf
