[supervisord]
nodaemon=true
user=root

[program:rsyslog]
command=rsyslogd -n -iNONE
priority=80

#[program:saslauthd]
#command=/usr/sbin/saslauthd -a pam -n 10 -c -m /var/run/saslauthd -l -d

[program:cyrusimap]
command=/usr/sbin/cyrmaster -M /etc/cyrus-conf/cyrus.conf -C /etc/cyrus-conf/imapd.conf
